### ISSUE TITLE
Screenshot of the dream

### ISSUE THREAD

**Issue by billylanchantin** [spawnfest/graphql_smart_cell#11]
<img width="962" alt="Screen Shot 2022-10-16 at 7 29 35 PM" src="https://user-images.githubusercontent.com/10274508/196064112-558e4d5f-1f7e-452e-81b6-89d1e3f30419.png">

**Comment by mcrumm** [comment]
Client:
<img width="936" alt="Screen Shot 2022-10-16 at 4 33 45 PM" src="https://user-images.githubusercontent.com/168677/196064401-fd0eac29-98ba-4263-8a9d-6b0acea8e23b.png">

Query:

<img width="967" alt="Screen Shot 2022-10-16 at 4 34 55 PM" src="https://user-images.githubusercontent.com/168677/196064395-a663987c-a34e-4177-8bbc-b67512faae02.png">
